export const alltasks = [
  {
    id: 1,
    category: "ongoing tasks",
    tasks: [
      {
        id: 1,
        status: "ongoing",
        taskName: "introduction",
        dueDate: "",
        createOn: "today",
        tags: ["mobile", "website", "+2"],
        timer: "30 minutes",
      },
      {
        id: 2,
        status: "ongoing",
        taskName: "getting started with frontend",
        dueDate: "",
        createOn: "yesterday",
        tags: ["mobile", "website", "+2"],
        timer: "01:59:59",
      },
      {
        id: 3,
        status: "ongoing",
        taskName: "gatting started",
        dueDate: "",
        createOn: "two weeks ago",
        tags: ["mobile", "website", "+2"],
        timer: "01:59:59",
      },
    ],
  },
  {
    id: 2,
    category: "upcoming tasks",
    tasks: [
      {
        id: 4,
        status: "upComing",
        taskName: "introduction",
        dueDate: "3 day",
        createOn: "today",
        tags: ["mobile", "website", "+2"],
        timer: "N/A",
      },
      {
        id: 5,
        status: "upComing",
        taskName: "getting started with frontend",
        dueDate: "sept 13",
        createOn: "yesterday",
        tags: ["mobile", "website", "+2"],
        timer: "N/A",
      },
    ],
  },
  {
    id: 3,
    category: "feature tasks",
    tasks: [
      {
        id: 6,
        status: "featureTask",
        taskName: "introduction",
        dueDate: "",
        createOn: "today",
        tags: ["mobile", "website", "+2"],
        timer: "N/A",
      },
      {
        id: 7,
        status: "featureTask",
        taskName: "getting started with frontend",
        dueDate: "",
        createOn: "yesterday",
        tags: ["mobile", "website", "+2"],
        timer: "N/A",
      },
    ],
  },
  {
    id: 4,
    category: "completed tasks",
    tasks: [
      {
        id: 1,
        status: "completedTask",
        taskName: "introduction",
        dueDate: "",
        createOn: "today",
        tags: ["mobile", "website", "+2"],
        timer: "N/A",
      },
      {
        id: 2,
        status: "completedTask",
        taskName: "getting started with frontend",
        dueDate: "",
        createOn: "yesterday",
        tags: ["mobile", "website", "+2"],
        timer: "N/A",
      },
    ],
  },
];
